spring.application.name=email-service
spring.config.import=optional:file:.env[.properties]
# ===================== SERVER =====================
server.port=${EMAIL_SERVICE_PORT}

# ===================== KAFKA CONSUMER =====================
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=email-group-v4
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

# \u2705 MUST: ErrorHandlingDeserializer (fixes your exact error)
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# \u2705 Delegate actual deserializers
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# \u2705 CRITICAL JSON FIXES
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.vinayak.common.dto.NotificationEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# ===================== KAFKA LISTENER =====================
spring.kafka.listener.ack-mode=record
spring.kafka.listener.concurrency=1

# ===================== EMAIL CONFIG =====================
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true